[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = ' [$user]($style) '

[hostname]
ssh_only = false
format = 'on [$hostname](bold yellow) '

[directory]
truncation_symbol = ".../"
truncate_to_repo = false
home_symbol = "~"  # Or try something like ï€•, ó°‹œ, ï€„, ğŸ¡
style = "bold cyan"
format = "[ó°£‡](bold blue)  [$path]($style) "


[python]
symbol = "îœ¼  "
# Or use a Nerd Font symbol like
# symbol = "îœ¼"  # Nerd Font python icon
